### ISSUE TITLE
is there a Yolov7-Segmentation tiny version?

### ISSUE THREAD

**Issue by guillermoecn** [leandro-svg/yolov7_trt#1]
Hello, i would like to know if a tiny version for segmentation exists? I have used TensorRT to optimize my model but i would like to have a little more of speed.
Thanks

**Comment by leandro-svg** [comment]
Dear @guillermoecn, thank you for reaching out.

According to @WongKinYiu 's github (
 https://github.com/WongKinYiu/yolov7/tree/u7/seg), it doesn't look like he has added other trained model. There have been Yolov7 and Yolov7-X only.
What you could do aswell is training your own model with this method and your own parameters : https://github.com/RizwanMunawar/yolov7-segmentation. As a note, object detection YOLOv7-tiny is an edge GPU-oriented archi-
tecture, it will use leaky ReLU as activation function.

Or depending on the application, reducing the input image size, as I did for my personal work on edge device such as Nvidia Jetson TX2.

Good luck and sorry for not being able to answer you correctly.
